/* Homepage collections + inquiry link. Full gallery pages are generated from portfolio.json. */
window.REVIVE_CONTENT = {
  "typeformUrl": "https://form.typeform.com/to/akWqAavH",
  "portfolio": [
    {
      "image": "assets/web/portfolio-fit-1800.webp",
      "thumbnail": "assets/web/portfolio-fit-640.webp",
      "alt": "White blouse and green pleated skirt in a mirror outfit detail",
      "width": 1350,
      "height": 1800,
      "srcset": "assets/web/portfolio-fit-640.webp 480w, assets/web/portfolio-fit-1800.webp 1350w",
      "caption": "Clothing / Beauty",
      "theme": "style",
      "collage": [
        {
          "photo": "fit",
          "x": 0,
          "y": 0,
          "w": 26,
          "h": 62,
          "image": "assets/web/portfolio-fit-1800.webp",
          "thumbnail": "assets/web/portfolio-fit-640.webp",
          "alt": "White blouse and green pleated skirt in a mirror outfit detail",
          "width": 1350,
          "height": 1800,
          "srcset": "assets/web/portfolio-fit-640.webp 480w, assets/web/portfolio-fit-1800.webp 1350w"
        },
        {
          "photo": "clothingrack",
          "x": 22.7,
          "y": 0,
          "w": 34.5,
          "h": 29.5,
          "image": "assets/web/portfolio-clothingrack-1800.webp",
          "thumbnail": "assets/web/portfolio-clothingrack-640.webp",
          "alt": "Clothing arranged on pink hangers beneath a painting",
          "width": 1800,
          "height": 1350,
          "srcset": "assets/web/portfolio-clothingrack-640.webp 640w, assets/web/portfolio-clothingrack-1800.webp 1800w"
        },
        {
          "photo": "heyurcute",
          "x": 73,
          "y": 0,
          "w": 25,
          "h": 50,
          "image": "assets/web/portfolio-heyurcute-1800.webp",
          "thumbnail": "assets/web/portfolio-heyurcute-640.webp",
          "alt": "A pink and yellow floral tote bag on patterned bedding",
          "width": 1350,
          "height": 1800,
          "srcset": "assets/web/portfolio-heyurcute-640.webp 480w, assets/web/portfolio-heyurcute-1800.webp 1350w"
        },
        {
          "photo": "bently",
          "x": 28,
          "y": 32.5,
          "w": 22.5,
          "h": 63.5,
          "image": "assets/web/portfolio-bently-1800.webp",
          "thumbnail": "assets/web/portfolio-bently-640.webp",
          "alt": "An open fashion book styled with folded denim and a blue bag",
          "width": 1350,
          "height": 1800,
          "srcset": "assets/web/portfolio-bently-640.webp 480w, assets/web/portfolio-bently-1800.webp 1350w"
        },
        {
          "photo": "boots",
          "x": 52.4,
          "y": 23.7,
          "w": 16.5,
          "h": 35.2,
          "layer": 3,
          "image": "assets/web/portfolio-boots-1800.webp",
          "thumbnail": "assets/web/portfolio-boots-640.webp",
          "alt": "Patterned heeled boots resting against a paneled wall",
          "width": 1440,
          "height": 1800,
          "srcset": "assets/web/portfolio-boots-640.webp 512w, assets/web/portfolio-boots-1800.webp 1440w"
        },
        {
          "photo": "vogue",
          "x": 62.2,
          "y": 53.5,
          "w": 35,
          "h": 46.5,
          "image": "assets/web/portfolio-vogue-1800.webp",
          "thumbnail": "assets/web/portfolio-vogue-640.webp",
          "alt": "Purple graphic T-shirt and dark denim in the sunshine",
          "width": 1800,
          "height": 1350,
          "srcset": "assets/web/portfolio-vogue-640.webp 640w, assets/web/portfolio-vogue-1800.webp 1800w"
        },
        {
          "photo": "fitfire",
          "x": 4.5,
          "y": 64.2,
          "w": 17,
          "h": 35.8,
          "image": "assets/web/portfolio-fitfire-1800.webp",
          "thumbnail": "assets/web/portfolio-fitfire-640.webp",
          "alt": "Pink sweatshirt, denim shorts and white high-top sneakers",
          "width": 1350,
          "height": 1800,
          "srcset": "assets/web/portfolio-fitfire-640.webp 480w, assets/web/portfolio-fitfire-1800.webp 1350w"
        }
      ],
      "href": "work-clothing-beauty.html",
      "count": 16
    },
    {
      "image": "assets/web/portfolio-montenegro-1800.webp",
      "thumbnail": "assets/web/portfolio-montenegro-640.webp",
      "alt": "A green mountain valley beneath bright clouds",
      "width": 1800,
      "height": 1350,
      "srcset": "assets/web/portfolio-montenegro-640.webp 640w, assets/web/portfolio-montenegro-1800.webp 1800w",
      "caption": "Destination",
      "theme": "destination",
      "collage": [
        {
          "photo": "home-jpg",
          "x": 0,
          "y": 0,
          "w": 38.1,
          "h": 100,
          "image": "assets/web/portfolio-home-jpg-1800.webp",
          "thumbnail": "assets/web/portfolio-home-jpg-640.webp",
          "alt": "Pale blue evening sky and moon above a house",
          "width": 1350,
          "height": 1800,
          "srcset": "assets/web/portfolio-home-jpg-640.webp 480w, assets/web/portfolio-home-jpg-1800.webp 1350w"
        },
        {
          "photo": "lakeroosevelt",
          "x": 5.6,
          "y": 15.2,
          "w": 27,
          "h": 64,
          "layer": 2,
          "image": "assets/web/portfolio-lakeroosevelt-1800.webp",
          "thumbnail": "assets/web/portfolio-lakeroosevelt-640.webp",
          "alt": "People gathered around a fire outside a house at dusk",
          "width": 1350,
          "height": 1800,
          "srcset": "assets/web/portfolio-lakeroosevelt-640.webp 480w, assets/web/portfolio-lakeroosevelt-1800.webp 1350w"
        },
        {
          "photo": "floridapool",
          "x": 38.1,
          "y": 0,
          "w": 20.7,
          "h": 52.3,
          "image": "assets/web/portfolio-floridapool-1800.webp",
          "thumbnail": "assets/web/portfolio-floridapool-640.webp",
          "alt": "Turquoise swimming pool framed by palm trees and blue sky",
          "width": 1350,
          "height": 1800,
          "srcset": "assets/web/portfolio-floridapool-640.webp 480w, assets/web/portfolio-floridapool-1800.webp 1350w"
        },
        {
          "photo": "mountainfarm",
          "x": 58.8,
          "y": 0,
          "w": 19.6,
          "h": 52.3,
          "image": "assets/web/portfolio-mountainfarm-1800.webp",
          "thumbnail": "assets/web/portfolio-mountainfarm-640.webp",
          "alt": "A red tractor and blue trailer below green mountains",
          "width": 1350,
          "height": 1800,
          "srcset": "assets/web/portfolio-mountainfarm-640.webp 480w, assets/web/portfolio-mountainfarm-1800.webp 1350w"
        },
        {
          "photo": "oregonhouse",
          "x": 78.4,
          "y": 0,
          "w": 21.6,
          "h": 52.3,
          "image": "assets/web/portfolio-oregonhouse-1800.webp",
          "thumbnail": "assets/web/portfolio-oregonhouse-640.webp",
          "alt": "Light-filled living room with a vaulted wooden ceiling and tall windows",
          "width": 1350,
          "height": 1800,
          "srcset": "assets/web/portfolio-oregonhouse-640.webp 480w, assets/web/portfolio-oregonhouse-1800.webp 1350w"
        },
        {
          "photo": "met",
          "x": 38.1,
          "y": 52.3,
          "w": 21.7,
          "h": 47.7,
          "image": "assets/web/portfolio-met-1800.webp",
          "thumbnail": "assets/web/portfolio-met-640.webp",
          "alt": "A visitor sketching beside a marble sculpture in a museum",
          "width": 1350,
          "height": 1800,
          "srcset": "assets/web/portfolio-met-640.webp 480w, assets/web/portfolio-met-1800.webp 1350w"
        },
        {
          "photo": "montenegro",
          "x": 59.8,
          "y": 52.3,
          "w": 40.2,
          "h": 47.7,
          "image": "assets/web/portfolio-montenegro-1800.webp",
          "thumbnail": "assets/web/portfolio-montenegro-640.webp",
          "alt": "A green mountain valley beneath bright clouds",
          "width": 1800,
          "height": 1350,
          "srcset": "assets/web/portfolio-montenegro-640.webp 640w, assets/web/portfolio-montenegro-1800.webp 1800w"
        }
      ],
      "href": "work-destination.html",
      "count": 11
    },
    {
      "image": "assets/web/portfolio-earlgrey-1800.webp",
      "thumbnail": "assets/web/portfolio-earlgrey-640.webp",
      "alt": "Cream swirling into a glass of tea beside small ceramic cups",
      "width": 1800,
      "height": 1800,
      "srcset": "assets/web/portfolio-earlgrey-640.webp 640w, assets/web/portfolio-earlgrey-1800.webp 1800w",
      "caption": "Food & Drink",
      "theme": "food",
      "collage": [
        {
          "photo": "marg1",
          "x": 0,
          "y": 0,
          "w": 28.3,
          "h": 46,
          "image": "assets/web/portfolio-marg1-1800.webp",
          "thumbnail": "assets/web/portfolio-marg1-640.webp",
          "alt": "An overhead view of a red-rimmed cocktail with cucumber and citrus",
          "width": 1350,
          "height": 1800,
          "srcset": "assets/web/portfolio-marg1-640.webp 480w, assets/web/portfolio-marg1-1800.webp 1350w"
        },
        {
          "photo": "brunch",
          "x": 28.3,
          "y": 0,
          "w": 23.1,
          "h": 46,
          "image": "assets/web/portfolio-brunch-1800.webp",
          "thumbnail": "assets/web/portfolio-brunch-640.webp",
          "alt": "Eggs Benedict and leafy greens on a cafe table",
          "width": 819,
          "height": 1042,
          "srcset": "assets/web/portfolio-brunch-640.webp 503w, assets/web/portfolio-brunch-1800.webp 819w"
        },
        {
          "photo": "coolgirlfame",
          "x": 51.4,
          "y": 0,
          "w": 24.5,
          "h": 46,
          "image": "assets/web/portfolio-coolgirlfame-1800.webp",
          "thumbnail": "assets/web/portfolio-coolgirlfame-640.webp",
          "alt": "Two people holding iced coffee and matcha outside a cafe",
          "width": 1517,
          "height": 1800,
          "srcset": "assets/web/portfolio-coolgirlfame-640.webp 539w, assets/web/portfolio-coolgirlfame-1800.webp 1517w"
        },
        {
          "photo": "charcuteri",
          "x": 75.9,
          "y": 0,
          "w": 24.1,
          "h": 100,
          "image": "assets/web/portfolio-charcuteri-1800.webp",
          "thumbnail": "assets/web/portfolio-charcuteri-640.webp",
          "alt": "Cheese, fruit, crackers and sliced meats arranged on a grazing board",
          "width": 1383,
          "height": 1800,
          "srcset": "assets/web/portfolio-charcuteri-640.webp 491w, assets/web/portfolio-charcuteri-1800.webp 1383w"
        },
        {
          "photo": "earlgrey",
          "x": 0,
          "y": 46,
          "w": 28.3,
          "h": 54,
          "image": "assets/web/portfolio-earlgrey-1800.webp",
          "thumbnail": "assets/web/portfolio-earlgrey-640.webp",
          "alt": "Cream swirling into a glass of tea beside small ceramic cups",
          "width": 1800,
          "height": 1800,
          "srcset": "assets/web/portfolio-earlgrey-640.webp 640w, assets/web/portfolio-earlgrey-1800.webp 1800w"
        },
        {
          "photo": "coffeefame",
          "x": 28.3,
          "y": 46,
          "w": 23.1,
          "h": 54,
          "image": "assets/web/portfolio-coffeefame-1800.webp",
          "thumbnail": "assets/web/portfolio-coffeefame-640.webp",
          "alt": "Iced coffee and a breakfast sandwich on a cafe table",
          "width": 1248,
          "height": 1800,
          "srcset": "assets/web/portfolio-coffeefame-640.webp 444w, assets/web/portfolio-coffeefame-1800.webp 1248w"
        },
        {
          "photo": "turkeysando",
          "x": 51.4,
          "y": 46,
          "w": 24.5,
          "h": 54,
          "image": "assets/web/portfolio-turkeysando-1800.webp",
          "thumbnail": "assets/web/portfolio-turkeysando-640.webp",
          "alt": "A toasted sandwich, potato wedges and a pickle on a cafe table",
          "width": 1350,
          "height": 1800,
          "srcset": "assets/web/portfolio-turkeysando-640.webp 480w, assets/web/portfolio-turkeysando-1800.webp 1350w"
        }
      ],
      "href": "work-food-drink.html",
      "count": 16
    },
    {
      "image": "assets/web/portfolio-champagnelanes-1800.webp",
      "thumbnail": "assets/web/portfolio-champagnelanes-640.webp",
      "alt": "Friends dressed up around a table in a colorful cocktail bar",
      "width": 1440,
      "height": 1800,
      "srcset": "assets/web/portfolio-champagnelanes-640.webp 512w, assets/web/portfolio-champagnelanes-1800.webp 1440w",
      "caption": "Event",
      "theme": "event",
      "collage": [
        {
          "photo": "champagnelanes",
          "x": 39.8,
          "y": 0,
          "w": 31.5,
          "h": 69,
          "image": "assets/web/portfolio-champagnelanes-1800.webp",
          "thumbnail": "assets/web/portfolio-champagnelanes-640.webp",
          "alt": "Friends dressed up around a table in a colorful cocktail bar",
          "width": 1440,
          "height": 1800,
          "srcset": "assets/web/portfolio-champagnelanes-640.webp 512w, assets/web/portfolio-champagnelanes-1800.webp 1440w"
        },
        {
          "photo": "celebration",
          "x": 0,
          "y": 0,
          "w": 33.9,
          "h": 40.5,
          "image": "assets/web/portfolio-celebration-1800.webp",
          "thumbnail": "assets/web/portfolio-celebration-640.webp",
          "alt": "Friends dressed up and celebrating together",
          "width": 960,
          "height": 641,
          "srcset": "assets/web/portfolio-celebration-640.webp 640w, assets/web/portfolio-celebration-1800.webp 960w"
        },
        {
          "photo": "starbeach",
          "x": 0,
          "y": 40.5,
          "w": 28.1,
          "h": 59.5,
          "image": "assets/web/portfolio-starbeach-1800.webp",
          "thumbnail": "assets/web/portfolio-starbeach-640.webp",
          "alt": "Friends gathered on the sand beside the ocean",
          "width": 1445,
          "height": 1800,
          "srcset": "assets/web/portfolio-starbeach-640.webp 514w, assets/web/portfolio-starbeach-1800.webp 1445w"
        },
        {
          "photo": "jonb",
          "x": 71.3,
          "y": 32.2,
          "w": 28.7,
          "h": 67.8,
          "image": "assets/web/portfolio-jonb-1800.webp",
          "thumbnail": "assets/web/portfolio-jonb-640.webp",
          "alt": "A crowd gathered at an outdoor waterfront venue at sunset",
          "width": 1350,
          "height": 1800,
          "srcset": "assets/web/portfolio-jonb-640.webp 480w, assets/web/portfolio-jonb-1800.webp 1350w"
        },
        {
          "photo": "coffee-cutout",
          "x": 28,
          "y": 35,
          "w": 25,
          "h": 65,
          "layer": 3,
          "cutout": true,
          "image": "assets/web/portfolio-coffee-cutout-1800.webp",
          "thumbnail": "assets/web/portfolio-coffee-cutout-640.webp",
          "alt": "A person in a Have More Fun cap holding an iced coffee",
          "width": 1001,
          "height": 1500,
          "srcset": "assets/web/portfolio-coffee-cutout-640.webp 427w, assets/web/portfolio-coffee-cutout-1800.webp 1001w"
        }
      ],
      "href": "work-event.html",
      "count": 9
    }
  ]
};
