(() => {
  const content = window.REVIVE_CONTENT || {typeformUrl:'', portfolio:[]};
  const container = document.querySelector('#photoEntries');
  document.querySelector('#typeformUrl').value = content.typeformUrl || '';
  let counter = 0;
  function addPhoto(item = {}) {
    const id = ++counter;
    const fieldset = document.createElement('fieldset');
    const legend = document.createElement('legend'); legend.textContent = `Photo ${id}`; fieldset.append(legend);
    for (const [key,label,placeholder] of [['image','Photo path','assets/portfolio-photos/my-photo.jpg'],['alt','Describe the photo (for accessibility)','E.g. a sunlit cafe terrace'],['caption','Caption','A few words about this moment']]) {
      const wrapper = document.createElement('label'); wrapper.textContent = label;
      const input = document.createElement('input'); input.name=key; input.value=item[key] || ''; input.placeholder=placeholder; input.required=key!=='caption'; wrapper.append(input); fieldset.append(wrapper);
    }
    const label = document.createElement('label'); label.textContent='Photo shape';
    const select=document.createElement('select'); select.name='layout';
    for (const [value,text] of [['','Standard'],['tall','Tall portrait'],['wide','Wide landscape']]) { const option=document.createElement('option'); option.value=value; option.textContent=text; select.append(option); }
    select.value=item.layout || ''; label.append(select); fieldset.append(label);
    const remove=document.createElement('button'); remove.type='button'; remove.textContent='Remove from this list'; remove.addEventListener('click',()=>fieldset.remove()); fieldset.append(remove); container.append(fieldset);
  }
  content.portfolio.forEach(addPhoto);
  document.querySelector('#addPhoto').addEventListener('click',()=>addPhoto());
  document.querySelector('#editor').addEventListener('submit',event=>{
    event.preventDefault();
    const status=document.querySelector('#status'); const typeformUrl=document.querySelector('#typeformUrl').value.trim();
    if(typeformUrl && !typeformUrl.startsWith('https://')) { status.textContent='Please use a complete secure https:// form link.'; return; }
    const portfolio=[...container.querySelectorAll('fieldset')].map(fieldset=>Object.fromEntries([...fieldset.querySelectorAll('input, select')].map(input=>[input.name,input.value.trim()])));
    if(!portfolio.length) { status.textContent='Keep at least one portfolio image.'; return; }
    if(portfolio.some(item=>!item.image.startsWith('assets/')||item.image.includes('..'))) { status.textContent='Each image path must begin with assets/ and stay inside that folder.'; return; }
    const output='/* Revive content — generated by the local content helper. */\nwindow.REVIVE_CONTENT = '+JSON.stringify({typeformUrl,portfolio},null,2)+';\n';
    const url=URL.createObjectURL(new Blob([output],{type:'text/javascript'})); const link=document.createElement('a'); link.href=url; link.download='content.js'; link.click(); setTimeout(()=>URL.revokeObjectURL(url),1000);
    status.textContent='Downloaded. Replace content.js in GitHub → Revive → revive-v3, upload any new photos, and redeploy. Your design stays the same.';
  });
})();
